# Semana 2 - Estructuras básicas, NumPy y Pandas

**Programa:** Tecnólogo en Análisis y Desarrollo de Software (ADSO)  
**Asignatura:** Ciencia de Datos  
**Institución:** SENA  
**Aprendiz:** Fernando José Zapa Portillo

## Objetivo

Aplicar estructuras básicas de Python, NumPy y Pandas para organizar,
procesar, analizar y exportar información mediante ejercicios prácticos.

## Actividades

1. Listas y diccionarios.
2. Operaciones con NumPy.
3. Series y DataFrames con Pandas.
4. Lectura y escritura de archivos CSV y Excel.
5. Inspección y análisis de datos.
6. Exportación de resultados y conclusiones.

## Actividad 3.2 - Listas y diccionarios

En esta actividad se utilizan estructuras básicas de Python para almacenar,
consultar y procesar información de productos.

Se desarrollan operaciones de recorrido, filtrado y cálculo de valores.

In [33]:
# Actividad 3.2 - Listas y diccionarios

# Lista de productos
productos = ["Cemento", "Arena", "Triturado", "Varilla", "Ladrillo"]

# Mostrar todos los productos
print("LISTA DE PRODUCTOS")

for producto in productos:
    print("-", producto)

# Consultar un producto específico
print("\nPrimer producto:", productos[0])

# Cantidad de productos
print("Total de productos:", len(productos))

LISTA DE PRODUCTOS
- Cemento
- Arena
- Triturado
- Varilla
- Ladrillo

Primer producto: Cemento
Total de productos: 5

In [34]:
# Diccionario con información de un producto

producto = {
    "nombre": "Cemento",
    "precio": 35000,
    "cantidad": 20,
    "categoria": "Materiales de construcción"
}

print("INFORMACIÓN DEL PRODUCTO")

print("Nombre:", producto["nombre"])
print("Precio:", producto["precio"])
print("Cantidad:", producto["cantidad"])
print("Categoría:", producto["categoria"])

# Calcular el valor total del inventario
valor_total = producto["precio"] * producto["cantidad"]

print("Valor total:", valor_total)

INFORMACIÓN DEL PRODUCTO
Nombre: Cemento
Precio: 35000
Cantidad: 20
Categoría: Materiales de construcción
Valor total: 700000

### Filtrado y procesamiento de información

En este ejercicio se utiliza una lista de diccionarios para representar
un inventario de materiales de construcción.

Se aplican filtros, recorridos y operaciones matemáticas para obtener
información útil a partir de los datos almacenados.

In [35]:
# Inventario representado mediante una lista de diccionarios

inventario = [
    {"nombre": "Cemento", "precio": 35000, "cantidad": 20},
    {"nombre": "Arena", "precio": 80000, "cantidad": 5},
    {"nombre": "Triturado", "precio": 90000, "cantidad": 8},
    {"nombre": "Varilla", "precio": 25000, "cantidad": 15},
    {"nombre": "Ladrillo", "precio": 1200, "cantidad": 500}
]

# Mostrar el inventario completo
print("INVENTARIO DE MATERIALES")

for material in inventario:
    print(
        material["nombre"],
        "- Precio:", material["precio"],
        "- Cantidad:", material["cantidad"]
    )

# Filtrar materiales cuyo precio sea mayor a 30000
print("\nMATERIALES CON PRECIO MAYOR A $30.000")

for material in inventario:
    if material["precio"] > 30000:
        print(material["nombre"], "-", material["precio"])

# Calcular el valor total del inventario
total_inventario = 0

for material in inventario:
    subtotal = material["precio"] * material["cantidad"]
    total_inventario += subtotal

print("\nVALOR TOTAL DEL INVENTARIO:", total_inventario)

INVENTARIO DE MATERIALES
Cemento - Precio: 35000 - Cantidad: 20
Arena - Precio: 80000 - Cantidad: 5
Triturado - Precio: 90000 - Cantidad: 8
Varilla - Precio: 25000 - Cantidad: 15
Ladrillo - Precio: 1200 - Cantidad: 500

MATERIALES CON PRECIO MAYOR A $30.000
Cemento - 35000
Arena - 80000
Triturado - 90000

VALOR TOTAL DEL INVENTARIO: 2795000

## Actividad 3.3 - Operaciones con NumPy

En esta actividad se utiliza la biblioteca NumPy para realizar
operaciones matemáticas y estadísticas sobre los precios de
materiales de construcción.

Se calculan la suma, el promedio, el valor máximo, el valor
mínimo y la desviación estándar.

In [36]:
# Actividad 3.3 - Operaciones con NumPy

import numpy as np

# Precios de los materiales
precios = np.array([35000, 80000, 90000, 25000, 1200])

print("PRECIOS DE LOS MATERIALES")
print(precios)

# Operaciones estadísticas
print("\nRESULTADOS ESTADÍSTICOS")

print("Cantidad de precios:", len(precios))
print("Suma de precios:", np.sum(precios))
print("Promedio:", np.mean(precios))
print("Precio máximo:", np.max(precios))
print("Precio mínimo:", np.min(precios))
print("Desviación estándar:", np.std(precios))

PRECIOS DE LOS MATERIALES
[35000 80000 90000 25000  1200]

RESULTADOS ESTADÍSTICOS
Cantidad de precios: 5
Suma de precios: 231200
Promedio: 46240.0
Precio máximo: 90000
Precio mínimo: 1200
Desviación estándar: 33647.44269628823

In [37]:
# Filtrar precios mayores a 30000

precios_altos = precios[precios > 30000]

print("PRECIOS MAYORES A $30.000")
print(precios_altos)

# Aplicar un incremento del 10 %
precios_incrementados = precios * 1.10

print("\nPRECIOS CON INCREMENTO DEL 10 %")
print(precios_incrementados)

PRECIOS MAYORES A $30.000
[35000 80000 90000]

PRECIOS CON INCREMENTO DEL 10 %
[38500. 88000. 99000. 27500.  1320.]

## Actividad 3.4 - Series y DataFrames con Pandas

En esta actividad se utiliza la biblioteca Pandas para organizar
información mediante estructuras Series y DataFrames.

Se construye una tabla de inventario de materiales de construcción,
se consultan sus registros y se realizan operaciones básicas de análisis.

In [38]:
# Actividad 3.4 - Series y DataFrames con Pandas

import pandas as pd

# Crear una Serie con los precios de los materiales
serie_precios = pd.Series(
    [35000, 80000, 90000, 25000, 1200],
    index=["Cemento", "Arena", "Triturado", "Varilla", "Ladrillo"]
)

print("SERIE DE PRECIOS")
print(serie_precios)

# Calcular estadísticas
print("\nPROMEDIO:", serie_precios.mean())
print("PRECIO MÁXIMO:", serie_precios.max())
print("PRECIO MÍNIMO:", serie_precios.min())

SERIE DE PRECIOS
Cemento      35000
Arena        80000
Triturado    90000
Varilla      25000
Ladrillo      1200
dtype: int64

PROMEDIO: 46240.0
PRECIO MÁXIMO: 90000
PRECIO MÍNIMO: 1200

In [39]:
# Crear un DataFrame a partir del inventario anterior

df_inventario = pd.DataFrame(inventario)

# Calcular el valor total por material
df_inventario["valor_total"] = (
    df_inventario["precio"] * df_inventario["cantidad"]
)

print("INVENTARIO DE MATERIALES")

display(df_inventario)

INVENTARIO DE MATERIALES

      nombre  precio  cantidad  valor_total
0    Cemento   35000        20       700000
1      Arena   80000         5       400000
2  Triturado   90000         8       720000
3    Varilla   25000        15       375000
4   Ladrillo    1200       500       600000

In [40]:
# Consultar los primeros registros
print("PRIMEROS REGISTROS")
display(df_inventario.head())

# Consultar información general
print("\nINFORMACIÓN DEL DATAFRAME")
df_inventario.info()

# Obtener estadísticas descriptivas
print("\nESTADÍSTICAS DESCRIPTIVAS")
display(df_inventario.describe())

# Filtrar materiales con precio mayor a 30000
print("\nMATERIALES CON PRECIO MAYOR A $30.000")

materiales_costosos = df_inventario[
    df_inventario["precio"] > 30000
]

display(materiales_costosos)

PRIMEROS REGISTROS

      nombre  precio  cantidad  valor_total
0    Cemento   35000        20       700000
1      Arena   80000         5       400000
2  Triturado   90000         8       720000
3    Varilla   25000        15       375000
4   Ladrillo    1200       500       600000

INFORMACIÓN DEL DATAFRAME
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nombre       5 non-null      str
 1   precio       5 non-null      int64
 2   cantidad     5 non-null      int64
 3   valor_total  5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 292.0 bytes

ESTADÍSTICAS DESCRIPTIVAS

             precio    cantidad    valor_total
count      5.000000    5.000000       5.000000
mean   46240.000000  109.600000  559000.000000
std    37618.984569  218.319262  163263.590552
min     1200.000000    5.000000  375000.000000
25%    25000.000000    8.000000  400000.000000
50%    35000.000000   15.000000  600000.000000
75%    80000.000000   20.000000  700000.000000
max    90000.000000  500.000000  720000.000000

MATERIALES CON PRECIO MAYOR A $30.000

      nombre  precio  cantidad  valor_total
0    Cemento   35000        20       700000
1      Arena   80000         5       400000
2  Triturado   90000         8       720000

## Actividad 3.5 - Lectura y escritura de archivos CSV y Excel

En esta actividad se utiliza Pandas para exportar información
de un DataFrame a archivos CSV y Excel.

Posteriormente, se importan los archivos generados para
verificar que la información se haya almacenado correctamente.

Los archivos se organizan en las carpetas data/raw y
data/processed del proyecto.

In [41]:
# Actividad 3.5 - Exportación de archivos

from pathlib import Path
import pandas as pd

# Ubicar la carpeta principal del proyecto
BASE_DIR = Path.cwd().resolve()

# Si estamos ejecutando desde notebooks, subir un nivel
if BASE_DIR.name == "notebooks":
    BASE_DIR = BASE_DIR.parent

# Definir carpeta para guardar archivos
carpeta_datos = BASE_DIR / "data" / "processed"

# Crear la carpeta si no existe
carpeta_datos.mkdir(parents=True, exist_ok=True)

# Definir las rutas
ruta_csv = carpeta_datos / "inventario_materiales.csv"
ruta_excel = carpeta_datos / "inventario_materiales.xlsx"

# Exportar los datos
df_inventario.to_csv(ruta_csv, index=False, encoding="utf-8-sig")

df_inventario.to_excel(ruta_excel, index=False)

print("ARCHIVOS EXPORTADOS CORRECTAMENTE")
print("CSV:", ruta_csv)
print("Excel:", ruta_excel)

ARCHIVOS EXPORTADOS CORRECTAMENTE
CSV: C:\7_trimestre\CienciaDatos\ciencia-datos-python\data\processed\inventario_materiales.csv
Excel: C:\7_trimestre\CienciaDatos\ciencia-datos-python\data\processed\inventario_materiales.xlsx

In [42]:
# Importar los archivos CSV y Excel

# Leer archivo CSV
df_csv = pd.read_csv(ruta_csv)

# Leer archivo Excel
df_excel = pd.read_excel(ruta_excel)

print("DATOS IMPORTADOS DESDE CSV")
display(df_csv)

print("\nDATOS IMPORTADOS DESDE EXCEL")
display(df_excel)

# Verificar que ambos archivos contienen los mismos datos
son_iguales = df_csv.equals(df_excel)

print("\n¿LOS ARCHIVOS CONTIENEN LOS MISMOS DATOS?")
print(son_iguales)

DATOS IMPORTADOS DESDE CSV

      nombre  precio  cantidad  valor_total
0    Cemento   35000        20       700000
1      Arena   80000         5       400000
2  Triturado   90000         8       720000
3    Varilla   25000        15       375000
4   Ladrillo    1200       500       600000

DATOS IMPORTADOS DESDE EXCEL

      nombre  precio  cantidad  valor_total
0    Cemento   35000        20       700000
1      Arena   80000         5       400000
2  Triturado   90000         8       720000
3    Varilla   25000        15       375000
4   Ladrillo    1200       500       600000

¿LOS ARCHIVOS CONTIENEN LOS MISMOS DATOS?
True

In [43]:
from pathlib import Path
import pandas as pd

# Obtener la carpeta principal del proyecto
BASE_DIR = Path.cwd().resolve()

if BASE_DIR.name == "notebooks":
    BASE_DIR = BASE_DIR.parent

# Definir la carpeta de destino
carpeta_datos = BASE_DIR / "data" / "processed"

# Crear la carpeta si no existe
carpeta_datos.mkdir(parents=True, exist_ok=True)

# Definir las rutas de los archivos
ruta_csv = carpeta_datos / "inventario_materiales.csv"
ruta_excel = carpeta_datos / "inventario_materiales.xlsx"

# Exportar el DataFrame que creamos anteriormente
df_inventario.to_csv(ruta_csv, index=False, encoding="utf-8-sig")
df_inventario.to_excel(ruta_excel, index=False)

# Verificar los archivos
print("Carpeta de destino:", carpeta_datos)
print("¿Existe el CSV?:", ruta_csv.exists())
print("¿Existe el Excel?:", ruta_excel.exists())

Carpeta de destino: C:\7_trimestre\CienciaDatos\ciencia-datos-python\data\processed
¿Existe el CSV?: True
¿Existe el Excel?: True

## Actividad 3.6 - Análisis de datos con Pandas

En esta actividad se realiza un análisis del inventario de materiales
de construcción utilizando Pandas.

Se calculan indicadores como el valor total del inventario,
el precio promedio, el material más costoso y el material
con mayor cantidad disponible.

El objetivo es transformar los datos almacenados en información
útil para la toma de decisiones.

In [44]:
# Actividad 3.6 - Análisis de datos

import pandas as pd

# Trabajar con los datos importados
df_analisis = df_csv.copy()

# Calcular indicadores generales
total_materiales = len(df_analisis)
valor_inventario = df_analisis["valor_total"].sum()
precio_promedio = df_analisis["precio"].mean()

# Identificar materiales destacados
material_costoso = df_analisis.loc[
    df_analisis["precio"].idxmax()
]

material_mayor_cantidad = df_analisis.loc[
    df_analisis["cantidad"].idxmax()
]

# Mostrar resultados
print("ANÁLISIS GENERAL DEL INVENTARIO")

print("Total de tipos de materiales:", total_materiales)
print("Valor total del inventario: $", valor_inventario)
print("Precio promedio por unidad: $", precio_promedio)

print("\nMATERIAL MÁS COSTOSO")
print("Nombre:", material_costoso["nombre"])
print("Precio: $", material_costoso["precio"])

print("\nMATERIAL CON MAYOR CANTIDAD")
print("Nombre:", material_mayor_cantidad["nombre"])
print("Cantidad:", material_mayor_cantidad["cantidad"])

ANÁLISIS GENERAL DEL INVENTARIO
Total de tipos de materiales: 5
Valor total del inventario: $ 2795000
Precio promedio por unidad: $ 46240.0

MATERIAL MÁS COSTOSO
Nombre: Triturado
Precio: $ 90000

MATERIAL CON MAYOR CANTIDAD
Nombre: Ladrillo
Cantidad: 500

## Actividad 3.7 - Interpretación de resultados y conclusiones

### Interpretación de resultados

Durante el desarrollo de esta actividad se analizaron cinco tipos de
materiales de construcción utilizando las bibliotecas NumPy y Pandas.

El análisis permitió identificar que el valor total del inventario
es de $2.795.000, mientras que el promedio de los precios unitarios
registrados es de $46.240.

El triturado presenta el precio unitario más alto, con un valor de
$90.000, mientras que el ladrillo tiene la mayor cantidad disponible,
con 500 unidades.

Estos resultados demuestran cómo el procesamiento de datos permite
obtener información útil para el control y seguimiento de inventarios.

### Conclusiones

1. Las listas y los diccionarios de Python permiten almacenar y
   organizar información de manera estructurada.

2. NumPy facilita la realización de operaciones matemáticas y
   estadísticas sobre conjuntos de datos.

3. Pandas permite organizar información en tablas, aplicar filtros
   y calcular indicadores para apoyar el análisis de datos.

4. Los archivos CSV y Excel facilitan el almacenamiento,
   intercambio y recuperación de información.

5. El uso de herramientas de ciencia de datos permite transformar
   registros en información útil para apoyar la toma de decisiones.

### Aprendizaje obtenido

Durante esta actividad aprendí a utilizar estructuras básicas de
Python, realizar cálculos con NumPy y trabajar con DataFrames
mediante Pandas.

También comprendí cómo importar y exportar archivos CSV y Excel,
consultar información y obtener indicadores estadísticos a partir
de datos organizados.